NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: ""
RUN_N_TIMES: 1
MODEL:
  TRANSFER_TYPE: "h2t-prompt"
  TYPE: "h2t-vit"
  LINEAR:
    MLP_SIZES: []
SOLVER:
  SCHEDULER: "cosine"
  PATIENCE: 300
  LOSS: "softmax"
  OPTIMIZER: "sgd"
  MOMENTUM: 0.9
  LOG_EVERY_N: 100
  WARMUP_EPOCH: 10
  TOTAL_EPOCH: 100
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.0001
DATA:
  NAME: ""
  NUMBER_CLASSES: -1
  DATAPATH: ""
  FEATURE: "sup_vitb16_224"
  BATCH_SIZE: 128
